### ISSUE TITLE
Prevent "unused" warning with wasm_bindgen_test

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1297]
Here's the test setup:

```toml
# Cargo.toml

[package]
name = "wasm-pack-unused-demo"
version = "0.1.0"
authors = ["Danilo <mail@dbrgn.ch>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.37"

[dev-dependencies]
wasm-bindgen-test = "0.2"
```

```rust
// tests/web.rs

#![cfg(target_arch = "wasm32")]
use wasm_bindgen_test::wasm_bindgen_test;

pub(crate) fn setup_test() {
    // do some setup magic
    assert_eq!(1, 1);
}

#[wasm_bindgen_test]
fn testing_works() {
    setup_test();
    assert_eq!(1 + 1, 2);
}
```

This builds without warnings and runs the test successfully.

```
$ cargo clean && wasm-pack test --headless --firefox
...
test result: ok. 1 passed; 0 failed; 0 ignored
```

However, as soon as I move the `setup_test` helper function to a separate module, I get warnings:

```rust
// tests/web.rs
#![cfg(target_arch = "wasm32")]

use wasm_bindgen_test::wasm_bindgen_test;

mod helpers;
use helpers::setup_test;

#[wasm_bindgen_test]
fn testing_works() {
    setup_test();
    assert_eq!(1 + 1, 2);
}
``` 

```rust
// tests/helpers.rs

pub(crate) fn setup_test() {
    // do some setup magic
    assert_eq!(1, 1);
}
```

This is the warning when testing:

```
  warning: function is never used: `setup_test`
   --> tests/helpers.rs:1:1
    |
  1 | pub(crate) fn setup_test() {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default
```

I can also stick a `#![cfg(target_arch = "wasm32")]` annotation into the `helpers.rs` module, that doesn't help either.

Is this some issue with the way the `#[wasm_bindgen_test]` macro is expanded? Can I resolve those warnings without simply silencing them (maybe with some kind of cfg guard)?
