### ISSUE TITLE
JsValue::into_serde raises an error when called with undefined

### ISSUE THREAD

**Issue by pustaczek** [rustwasm/wasm-bindgen#1778]
### Describe the Bug

When `JsValue::into_serde` is called on an `undefined` value, wasm-bindgen raises a JavaScript exception instead of returning an Err value. 

### Steps to Reproduce

Set up the following project:
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn hello(thing: JsValue) {
    let _: Result<i32, _> = thing.into_serde();
}
```
```toml
[package]
name = "oopsie"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
```

Build and package with `wasm-pack build --target nodejs`, launch `node` and try to call `hello` with `undefined`:
```js
let pkg = require('./pkg');
pkg.hello(undefined);
```

### Expected Behavior

The `Err` variant is returned. If the target type was an `Option<i32>`, the deserialization could also be successful.

### Actual Behavior

A JavaScript `TypeError` was thrown in the glue code:
```
> let pkg = require('./pkg');
undefined
> pkg.hello(undefined)
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at passStringToWasm (/home/matcegla/oopsie/pkg/oopsie.js:40:25)
    at module.exports.__wbindgen_json_serialize (/home/matcegla/oopsie/pkg/oopsie.js:69:18)
    at oopsie::hello::h4722553de1adeefa (wasm-function[50]:26)
    at hello (wasm-function[131]:3)
    at Object.module.exports.hello (/home/matcegla/oopsie/pkg/oopsie.js:23:10
```
