### ISSUE TITLE
Add configuration file options for wasm-bindgen cli

### ISSUE THREAD

**Issue by lynncyrin** [rustwasm/wasm-bindgen#196]
## current behavior

I generate dev vs prod builds with these two commands

```makefile
# makefile

wasm-build-dev:
	wasm-bindgen target/wasm32-unknown-unknown/debug/galaxy_gen.wasm --debug --out-dir src/js/assets/built-wasm --browser

wasm-build-prod:
	wasm-bindgen target/wasm32-unknown-unknown/debug/galaxy_gen.wasm --out-dir src/js/assets/built-wasm --browser
```

## desired behavior

the difference in the two commands that I call in makefile above is reduced to the difference between the `dev` and `prod` variants, so I get a makefile like so

```makefile
# makefile

wasm-build-dev:
	wasm-bindgen --debug

wasm-build-prod:
	wasm-bindgen
```

and add my `wasm-bindgen` config to `Cargo.toml` like so

```toml
# Cargo.toml

[wasm-bindgen]
    browser = true
    input = "target/wasm32-unknown-unknown/debug/galaxy_gen.wasm"
    out-dir = "src/js/assets/built-wasm"
```

## context

- [the project I'm using wasm-bindgen on](https://github.com/lynncyrin/galaxy-gen)
- [the (forked) heroku buildpack I'm using to build it](https://github.com/lynncyrin/heroku-buildpack-rust)
