### ISSUE TITLE
[web_sys] performance compiling error 

### ISSUE THREAD

**Issue by OAyomide** [rustwasm/wasm-bindgen#1964]
### Describe the Bug

Following the example in the wasm-bindgen reference/docs, when I compile (part of) the example code, it throws a compilation error.
### Steps to Reproduce

1. Copy the sample code
2. Compile using wasm-pack
3. Check JavaScript console to see error

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

It should print the current time in milliseconds 

### Actual Behavior

```Failed to compile.

./src/build/index.js
  Line 265:19:  'globalThis' is not defined  no-undef
  Line 274:19:  Unexpected use of 'self'     no-restricted-globals
```

### Additional Context
I am using this with React and while this changes nothing, its just noteworthy.
Here is the copied code:
```rust
#[wasm_bindgen(start)]
pub fn run_perf() {
  let window = web_sys::window().expect("should have a window in this context");
  let performance = window
    .performance()
    .expect("performance should be available");

  console_log!("the current time (in ms) is {}", performance.now());
}
```
and Cargo.toml
```toml
[dependencies]
wasm-bindgen = "0.2.58"
image = { version = "0.22.3"}
humantime = "1"

[dependencies.web-sys]
version = "0.3.4"
features = ['Window', 'Performance', 'PerformanceTiming', 'console']
```
If there's something I am not doing right, I'd appreciate some help.
