### ISSUE TITLE
Closures break wasm-opt

### ISSUE THREAD

**Issue by elslooo** [rustwasm/wasm-bindgen#2033]
### Steps to Reproduce

1. Put the following code into `src/lib.rs`:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn main() {
    let _ = Closure::once_into_js(Box::new(|| {
        // Hello World
    }) as Box<dyn FnMut()>);
}
```

2. Put the following code into `Cargo.toml`:

```toml
[package]
name = "wasm-test-case"
version = "0.1.0"
edition = "2018"

[lib]
name = "test"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2.59"
```

3. Put the following code in `Makefile`:
```bash
wasm:
	cargo build --lib --release --target wasm32-unknown-unknown
	wasm-opt -Oz ./target/wasm32-unknown-unknown/release/test.wasm -o ./target/wasm32-unknown-unknown/release/test.opt.wasm
	wasm-bindgen --no-demangle --target web --out-dir ./target/wasm32-unknown-unknown/release/ ./target/wasm32-unknown-unknown/release/test.opt.wasm
```

4. Run ```make wasm```. This will:
    - Build the test case for wasm using cargo (with or without release, doesn't matter).
    - Apply ```wasm-opt``` to the generated file and save it to ```test.2.wasm```.
    - Apply ```wasm-bindgen``` to ```test.opt.wasm```.

### Expected Behavior

This should not panic.

### Actual Behavior

This panicks with:

```
unknown instruction Block(Block { seq: Id { idx: 1 } })
```

This panic is caused by the ```wasm-bindgen-wasm-interpreter```. I suspect the optimizer is generating instructions that the interpreter doesn't expect? Is there a way to fix this, either a) by extending the interpreter or b) changing the Closure-code so that it doesn't emit this instruction?
