### ISSUE TITLE
Why Rust performs slower than Javascript?

### ISSUE THREAD

**Issue by reza-ebrahimi** [rustwasm/wasm-bindgen#2355]
Poor performance on sum of an array of 200 elements. The array is same for both Rust and Javascript.
Test is done on Chrome.

Cargo.toml:
```toml
[package]
name = "rust-webassembly"
version = "0.1.0"
authors = [""]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = 3
```

Rust code:
```rust
#[wasm_bindgen]
pub fn rust_sum() -> u32 {
    let elements = vec![91, 57, 74, 55, 6, 12, 94, 26, 96, 69, 85, 35, 0, 54, 8, 50, 44, 69, 22, 54, 61, 37, 38, 89, 94, 43, 58, 39, 37, 93, 20, 31, 32, 39, 48, 18, 26, 66, 14, 37, 59, 25, 86, 15, 52, 91, 25, 26, 94, 100, 29, 95, 75, 93, 16, 29, 89, 96, 33, 59, 3, 70, 46, 17, 55, 8, 77, 90, 36, 47, 2, 41, 3, 29, 49, 57, 49, 70, 24, 62, 28, 66, 29, 38, 70, 93, 12, 58, 100, 10, 80, 81, 73, 96, 59, 2, 48, 73, 35, 97, 48, 98, 7, 85, 85, 58, 72, 94, 46, 26, 57, 2, 54, 78, 63, 2, 59, 18, 32, 42, 90, 94, 64, 73, 41, 20, 45, 23, 15, 83, 35, 41, 45, 97, 12, 35, 21, 25, 39, 37, 17, 42, 23, 58, 56, 86, 77, 80, 18, 12, 57, 77, 99, 37, 68, 22, 2, 25, 54, 46, 59, 85, 5, 29, 45, 34, 86, 60, 41, 29, 97, 27, 26, 66, 44, 95, 87, 94, 8, 38, 77, 24, 46, 44, 13, 74, 55, 56, 20, 3, 31, 85, 59, 6, 65, 23, 22, 7, 12, 21];
    elements.iter().sum()
}
```

Javascript code:
```javascript
javascript_sum() {
  var elements = [91, 57, 74, 55, 6, 12, 94, 26, 96, 69, 85, 35, 0, 54, 8, 50, 44, 69, 22, 54, 61, 37, 38, 89, 94, 43, 58, 39, 37, 93, 20, 31, 32, 39, 48, 18, 26, 66, 14, 37, 59, 25, 86, 15, 52, 91, 25, 26, 94, 100, 29, 95, 75, 93, 16, 29, 89, 96, 33, 59, 3, 70, 46, 17, 55, 8, 77, 90, 36, 47, 2, 41, 3, 29, 49, 57, 49, 70, 24, 62, 28, 66, 29, 38, 70, 93, 12, 58, 100, 10, 80, 81, 73, 96, 59, 2, 48, 73, 35, 97, 48, 98, 7, 85, 85, 58, 72, 94, 46, 26, 57, 2, 54, 78, 63, 2, 59, 18, 32, 42, 90, 94, 64, 73, 41, 20, 45, 23, 15, 83, 35, 41, 45, 97, 12, 35, 21, 25, 39, 37, 17, 42, 23, 58, 56, 86, 77, 80, 18, 12, 57, 77, 99, 37, 68, 22, 2, 25, 54, 46, 59, 85, 5, 29, 45, 34, 86, 60, 41, 29, 97, 27, 26, 66, 44, 95, 87, 94, 8, 38, 77, 24, 46, 44, 13, 74, 55, 56, 20, 3, 31, 85, 59, 6, 65, 23, 22, 7, 12, 21];
  return elements.reduce((a, b) => a + b, 0);
}
```

Timing:
```javascript
console.time("javascript_sum");
var javascript_res = this.javascript_sum();
console.timeEnd("javascript_sum");

console.time("rust_sum");
var rust_res = nativeModule.rust_sum();
console.timeEnd("rust_sum");

console.assert(javascript_res === rust_res);
console.log("\n");
```

Console log:
```log
javascript_sum: 0.0087890625ms
rust_sum: 0.06591796875ms

javascript_sum: 0.009033203125ms
rust_sum: 0.160888671875ms

javascript_sum: 0.009033203125ms
rust_sum: 0.053955078125ms

javascript_sum: 0.0078125ms
rust_sum: 0.09814453125ms

javascript_sum: 0.009033203125ms
rust_sum: 0.08984375ms

javascript_sum: 0.0078125ms
rust_sum: 0.06005859375ms

javascript_sum: 0.009033203125ms
rust_sum: 0.093017578125ms

javascript_sum: 0.00927734375ms
rust_sum: 0.06396484375ms

javascript_sum: 0.029052734375ms
rust_sum: 0.113037109375ms

javascript_sum: 0.010009765625ms
rust_sum: 0.0810546875ms

javascript_sum: 0.009033203125ms
rust_sum: 0.053955078125ms
```
