### ISSUE TITLE
wasm-bindgen generated wrappers are leaked in docs

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-bindgen#2485]
### Describe the Bug

wasm-bindgen generated wrappers are leaked in `cargo doc` output.

### Steps to Reproduce

Try to run `cargo doc` on any example, e.g. this minimal sample:

```toml
[package]
name = "temp"
version = "0.1.0"
authors = ["Ingvar Stepanyan <rreverser@google.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
```

```rs
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn foo() -> i32 {
    42
}
```

and open the result in browser.

### Expected Behavior

Only `foo` is shown in the listing as an exported function.

### Actual Behavior

The output contains `foo` as well as internal `__wasm_bindgen_generated_foo` wrapper:

![image](https://user-images.githubusercontent.com/557590/110356535-463c2900-8032-11eb-8682-9919df84884a.png)

### Additional Context

In theory, this was fixed back in https://github.com/rustwasm/wasm-bindgen/pull/428 so I guess it's a regression?
