### ISSUE TITLE
Please help. Uncaught TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by githubmann** [rustwasm/wasm-bindgen#2791]
### Summary
tap `wasm-pack build` to get pkg folder, but It throw `wasm.__wbindgen_add_to_stack_pointer is not a function`  when I call `FmOsc.new()` 
A clear and concise summary of your question.

#### lib.rs
```rust
#![allow(unused_variables)]
use std::cell::RefCell;
use std::rc::Rc;
use std::{collections::HashMap, convert::TryFrom, pin::Pin};

use js_sys::{ArrayBuffer, Object, Promise};
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::{future_to_promise, JsFuture};

use wasm_bindgen::prelude::*;
use web_sys::AudioContext;
use web_sys::{window, AudioBuffer, Request, Response};

#[wasm_bindgen]
pub struct FmOsc {
    ctx: Rc<RefCell<AudioContext>>,
    /// Overall gain (volume) control
    gain: Rc<RefCell<web_sys::GainNode>>,

    dest: Rc<RefCell<web_sys::AudioDestinationNode>>,
    buf_source: Rc<RefCell<web_sys::AudioBufferSourceNode>>,
    buf_map: Rc<RefCell<HashMap<String, AudioBuffer>>>,
}

impl Drop for FmOsc {
    fn drop(&mut self) {
        // let _ = self.ctx.close();
    }
}

async fn decrypt(data: AudioBuffer) -> AudioBuffer {
    // future_to_promise(async move {
    let mut rand_arry = [0u8; 128];
    let window = web_sys::window().unwrap();
    let crypto = window.crypto().unwrap();
    let counter = crypto
        .get_random_values_with_u8_array(&mut rand_arry)
        .unwrap();
    let subtleCrypto = crypto.subtle();
    // al_r.serialize()
    // let mal = serde_json::from_str(s).unwrap();
    let al: Object = JsValue::from_serde(
        r#"{
                    "name": "AES-CTR",
                    "length": 128,
                }"#,
    )
    .unwrap()
    .into();
    let key_usages: JsValue = JsValue::from_serde(r#"["encrypt"]"#).unwrap().into();
    let s = "1111111111".to_string();
    let key_data = js_sys::Uint8Array::from(s.as_bytes()).dyn_into().unwrap();
    let keyPromise = subtleCrypto
        .import_key_with_str(
            "raw",
            &key_data,
            "AES-CTR",
            true,
            &JsValue::from(r#"["encrypt"]"#),
        )
        .unwrap();
    let key = JsFuture::from(keyPromise)
        .await
        .unwrap()
        .dyn_into()
        .unwrap();

    let decryptedPromise = subtleCrypto
        .decrypt_with_object_and_buffer_source(&al, &key, &data)
        .unwrap();
    let decryptedData: AudioBuffer = JsFuture::from(decryptedPromise).await.unwrap().into();
    decryptedData

    // })
}

pub async fn loadBuffer(src: String) -> AudioBuffer {
    let mut opts = web_sys::RequestInit::new();
    opts.method("GET");
    opts.mode(web_sys::RequestMode::Cors);
    let request = Request::new_with_str_and_init(&src, &opts).unwrap();
    let window = window().unwrap();
    let resp_val = JsFuture::from(window.fetch_with_request(&request)).await.unwrap();
    let resp: Response = resp_val.dyn_into().unwrap();
    // let json = JsFuture::from(resp.json()?).await?;

    let buf_str = JsFuture::from(resp.array_buffer().unwrap()).await.unwrap();

    let buf: AudioBuffer = buf_str.into();
    let buf: AudioBuffer = decrypt(buf).await;
    buf
}
#[wasm_bindgen]
impl FmOsc {
    // #[wasm_bindgen]
    // self.buf_map.insert(src.to_string(), buf);
    // Ok(())
    // #[wasm_bindgen]
    pub fn play(&mut self, src: &str) -> Result<(), JsValue> {
        let buf_map = self.buf_map.borrow();
        let buf = buf_map.get(src);
        // let buf_source = self.buf_source.borrow().get(src);
        if let Some(a) = buf {
            self.buf_source.borrow_mut().set_buffer(buf);
            let rt = self.buf_source.borrow_mut().start()?;
            self.gain.borrow_mut().connect_with_audio_node(&self.dest.borrow());

            Ok(())
        } else {
            let src = src.to_owned();
            let buf_map = self.buf_map.clone();
            let buf_source = self.buf_source.clone();
            let gain = self.gain.clone();
            let dest = self.dest.clone();
            future_to_promise(async move {
                let buf = loadBuffer(src.clone()).await;
                let mut buf_map = buf_map.borrow_mut();
                buf_map.insert(src.clone(), buf);
                let buf = buf_map.get(&src);
                if let Some(a) = buf {
                    buf_source.borrow_mut().set_buffer(buf);
                    let rt = buf_source.borrow().start().unwrap();
                    gain.borrow().connect_with_audio_node(&dest.borrow());
                } else {

                };

                Ok(JsValue::from(1))
            });
            // self.play(src).await;
            Ok(())
        }
    }
    // #[wasm_bindgen(constructor)]
    pub fn new() -> Result<FmOsc, JsValue> {
        let ctx = web_sys::AudioContext::new()?;
        let dest = Rc::new(RefCell::new(ctx.destination()));
        let gain = Rc::new(RefCell::new(ctx.create_gain()?));
        let buf_source = Rc::new(RefCell::new(ctx.create_buffer_source()?));
        let buf_map = Rc::new(RefCell::new(HashMap::new()));

        Ok(FmOsc {
            ctx: Rc::new(RefCell::new(ctx)),
            dest,
            gain,
            buf_source,
            buf_map,
        })

        // Create our web audio objects.
    }
    pub fn play_test(&mut self) {
        let secret_key = "11111111111111".to_string();
    }

}
```

#### cargo.toml
```toml
[package]
name = "wasm-crypto-audio"
version = "0.1.0"
authors = ["unkown"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"]  }
js-sys = "0.3.55"
wasm-bindgen-futures = "0.4.24"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
[dependencies.web-sys]
version = "0.3.54"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'AudioContext',
  'AudioDestinationNode',
  'AudioNode',
  'AudioParam',
  'GainNode',
  'OscillatorNode',
  'OscillatorType',
  'Window',
  'Document',
  'MediaStream',
  'HtmlMediaElement',
  'MediaElementAudioSourceNode',
  'AudioBufferSourceNode',
  'AudioBuffer',
  'Crypto',
  'SubtleCrypto',
  'CryptoKey',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

```

#### wasm-crypto-audio_bg.js
```js
............
 /**
    * @param {string} src
    */
    play(src) {
        try {
            const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
            var ptr0 = passStringToWasm0(src, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
            var len0 = WASM_VECTOR_LEN;
            wasm.fmosc_play(retptr, this.ptr, ptr0, len0);
            var r0 = getInt32Memory0()[retptr / 4 + 0];
            var r1 = getInt32Memory0()[retptr / 4 + 1];
            if (r1) {
                throw takeObject(r0);
            }
        } finally {
            wasm.__wbindgen_add_to_stack_pointer(16);
        }
    }
................
```

#### index.js
```ts
import { FmOsc } from 'wasm-crypto-audio'
const f = new FmOsc()
f.play(audioSource)
```

Provide any additional details here.
