### ISSUE TITLE
Can I use webassembly in github Page?

### ISSUE THREAD

**Issue by hyuckkim** [rustwasm/wasm-bindgen#2814]
### Summary

Can I use webassembly in github Page?
If so, how to them?

### Additional Details

I made repositorys. 
https://hyuckkim.github.io/wasm/  
https://github.com/hyuckkim/wasm
https://github.com/hyuckkim/hello-wasm

It is my rust code.
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn ten() -> i32 {
    10
}
```
I is my Cargo toml.
```toml
[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"
authors = ["hyuckkim <monkeyhyuck@naver.com>"]
description = "A sample project with wasm-pack"
license = "MIT/apache-2.0"
repository = "https://github.com/hyuckkim/hello-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
```
I use `wasm-pack build --target web`

It is my typescript code.
```typescript
import * as rust from "./pkg/hello_wasm.js";
console.log(rust.ten());
```

![image](https://user-images.githubusercontent.com/53367179/154883899-05e21dc4-0646-44de-9b0f-5ae75b010ba9.png)
wasm was undefined.
![image](https://user-images.githubusercontent.com/53367179/154883998-3b1df68d-98ad-47aa-9273-2c53ff3f992d.png)
I guess init() was not executed.

Then obviously the import went wrong. By the way I don't know the proper import method. What to do. Or is it something I can't do at all? Can you find me if I have the same question?

Thanks for read it all.
