### ISSUE TITLE
`Element.current_target()` always points to the `HtmlBodyElement`

### ISSUE THREAD

**Issue by mfreeborn** [rustwasm/wasm-bindgen#2849]
web-sys 0.3.56
rustc 1.59.0
chrome Version 100.0.4896.60 (Official Build) (64-bit)
Ubuntu 20.04

I spent a long time going around in circles trying to get a handle for the html element I'm interacting with so that I can do some further processing. After a lot of print-debugging, I realised that whenever an event is received, `current_target()` appears to point to the `HtmlBodyElement`.

I would expect it to return a handle to the parent element from which the event was fired.

Here is a minimal yew app:

```rust
use yew::prelude::*;

#[function_component(App)]
pub fn app() -> Html {
    let oninput = {
        Callback::from(|e: InputEvent| {
            log::info!("{:?}", e.current_target()); // Some(EventTarget { obj: Object { obj: JsValue(HTMLBodyElement) } })
            log::info!("{:?}", e.target()); // Some(EventTarget { obj: Object { obj: JsValue(HTMLInputElement) } })
        })
    };

    html! {
        <input {oninput} />
    }
}

fn main() {
    wasm_logger::init(wasm_logger::Config::default());
    yew::start_app::<App>();
}
```

Here is the Cargo.toml:

```toml
[package]
name = "yew-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
wasm-logger = "0.2"
web-sys = "0.3.56"
yew = "0.19"
```

In the app I'm developing, I noticed this behaviour on an `<svg>` element, to which I had added a click handler (i.e. a `MouseEvent`). The `<svg>` element has several `<path>` element children. `Element.target()` correctly gives me either the `<svg>` or the `<path>` elements, but I specifically always want the `<svg>` element, which is what I would expect `current_target()` to do.
