### ISSUE TITLE
[web-sys] Unable to set Request header "Authorization"

### ISSUE THREAD

**Issue by Mindstan** [rustwasm/wasm-bindgen#3128]
### Describe the Bug

I’m trying to send a `Request` to a server which requires the `Authorization` header to be set with a token value. However, it looks like every attempt to edit the headers to send does nothing.

Might be related to latest comments in https://github.com/rustwasm/wasm-bindgen/issues/1135

### Steps to Reproduce
- By using `Request.headers().set()`:
    ```rust
    let mut opts = RequestInit::new();
    opts.method(method);
    opts.mode(RequestMode::NoCors);

    let url = "http://hostname/".to_string();
    let request = Request::new_with_str_and_init(&url, &opts)?;
    request
        .headers()
        .set("Authorization", "TOKEN VALUE")?;

    // prints "A u t h o r i z a t i o n :   O k ( N o n e )"
    console::log(&js_sys::Array::from(&serde_wasm_bindgen::to_value(&format!(
        "Authorization: {:?}",
        request.headers().get("Authorization")
    )).unwrap()));
    // sends the request without the header
    let window = web_sys::window().unwrap();
    let resp_value = JsFuture::from(window.fetch_with_request(&request)).await?;
    ```

- By using `RequestInit.headers()`:
    ```rust
    let mut opts = RequestInit::new();
    opts.method(method);
    opts.mode(RequestMode::NoCors);
    let headers: HashMap<String, String> = HashMap::from([
        ("Authorization".to_string(), "TOKEN VALUE".to_string())
    ]);
    opts.headers(&serde_wasm_bindgen::to_value(&headers).unwrap());

    let url = "http://hostname/".to_string();
    let request = Request::new_with_str_and_init(&url, &opts)?;

    // prints "A u t h o r i z a t i o n :   O k ( N o n e )"
    console::log(&js_sys::Array::from(&serde_wasm_bindgen::to_value(&format!(
        "Authorization: {:?}",
        request.headers().get("Authorization")
    )).unwrap()));
    // sends the request without the header
    let window = web_sys::window().unwrap();
    let resp_value = JsFuture::from(window.fetch_with_request(&request)).await?;
    ```

### Expected Behavior

The header `Authorization` is send with the request.

### Actual Behavior

The header `Authorization` cannot be set.

### Additional Context

Dependencies in `cargo.toml`:

```toml
[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde-wasm-bindgen = "0.4.3"
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59"
regex = "1"
lazy_static = "1.4.0"
async-trait = "0.1.57"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
url_encoded_data = "0.6.1"
getrandom = { version = "0.2.7", features = ["js"] }
gloo = "0.8.0"
yew = "0.19.3"

[dependencies.web-sys]
version = "0.3.59"
features = [
    "console",
    "Document",
    "Element",
    "Headers",
    "HtmlElement",
    "Node",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
]
```

Code compiled and served with `trunk`, executed in with Firefox (105.0) and Chromium on Linux.
