### ISSUE TITLE
i64 return type not working on nodejs target

### ISSUE THREAD

**Issue by devthane** [rustwasm/wasm-bindgen#3222]
### Describe the Bug

Importing a function that returns an i64 currently results in a Cannot convert to BigInt error

### Steps to Reproduce

1. Set up the following files:

```toml
# ./cargo.toml
[package]
name = "wasm-bindgen-bigint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
```

```javascript
// ./src/index.js
const big_num = 6255361224;

exports.get_big_num = () => {
    return big_num;
}
```

```rust
// ./src/lib.rs
use wasm_bindgen::prelude::*;

#[wasm_bindgen(module = "/src/index.js")]
extern "C" {
    #[wasm_bindgen]
    pub fn get_big_num() -> i64;
}

#[wasm_bindgen]
pub fn check_bigint() {
    let big_num = get_big_num();
    panic!("{}", big_num);
}
```

```javascript
// ./index.js

let pkg = import("./pkg/wasm_bindgen_bigint.js");

pkg.then((m) => {
    m.check_bigint();
})
```

2. run `cargo build --target wasm32-unknown-unknown --release`
3. and then: `wasm-bindgen --target nodejs --out-dir ./pkg ./target/wasm32-unknown-unknown/release/wasm_bindgen_bigint.wasm`
4. run `node index.ts`

### Expected Behavior

Expect a panic with just the number 6255361224 as output.

### Actual Behavior

Error returned: TypeError: Cannot convert 6255361224 to a BigInt

### Additional Context

node version: v19.3.0

This happens with any imported function if you set the return type to i64 even small numbers like 5.
