### ISSUE TITLE
wasm-pack --release generate 1.8Mb .wasm

### ISSUE THREAD

**Issue by dmarteau** [rustwasm/wasm-bindgen#3235]
### Describe the Bug

Sorry to bring back this topic again again but  I did not found any good answers.

According to https://rustwasm.github.io/docs/book/reference/code-size.html generated ,wasm in release code should be very small, but running `wasm-pack --release --target web` génerate a 1.8Mb .wasm !

Note that running - the now deprecated  - `wasm-gc` then reduce the code size to 28kb

When compiling that simple `lib.rs`:
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    pub fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
```
and Cargo.toml:
```toml
[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
```

### Steps to Reproduce

1. Genarate cargo project with the above code and configuration
2. execute `wasm-pack --release  --target web`
3. Look at the .wasm file generated in target/release 

### Expected Behavior

A size of 28Kb (as when running `wasm-gc`)

### Actual Behavior

The generated wasm file is 1.8 Mb

### Additional Context

* wasm-pack v0.10.3
* cargo 1.66.1 (ad779e08b 2023-01-10) 
* host: x86_64-unknown-linux-gnu
Active toolchain:
* stable-x86_64-unknown-linux-gnu (default)
* rustc 1.66.1 (90743e729 2023-01-10)
