### ISSUE TITLE
Execute the `wasm-pack test --node` command, in fact, it does not call the start function annotated with #[wasm_bindgen(start)].

### ISSUE THREAD

**Issue by baoyachi** [rustwasm/wasm-bindgen#3739]
The following are the dependencies of my project.  When I execute the `wasm-pack test --node` command, in fact, it does not call the`start` function annotated with `#[wasm_bindgen(start)]`.

```diff
pub static GLOBAL_DATA: OnceCell<Mutex<Vec<VerboseLog>>> = OnceCell::new();

#[wasm_bindgen(start)]
+ fn start() {
    GLOBAL_DATA.get_or_init(|| {
        let t = Default::default();
        init_with_level(Level::Trace).unwrap();
        t
    });
}
...
```

```bash
~  wasm-pack --version
wasm-pack 0.12.1

```

```toml
[dependencies]
serde-wasm-bindgen = "0.5"
serde_json = "1.0.108"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

```
