### ISSUE TITLE
Uncaught TypeError: Bare Specifier “env” Not Remapped in WASM Build

### ISSUE THREAD

**Issue by sundaram123krishnan** [rustwasm/wasm-bindgen#4002]
### Summary

Uncaught TypeError: The specifier “env” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.

### Additional Details

When building the pigg project for WebAssembly (WASM), an error occurs indicating that a bare specifier "env" is not properly remapped, causing a TypeError. This issue arises during the import of modules or dependencies in the WASM environment.

My Cargo.toml file:

```toml
[package]
name = "pigg"
version = "0.2.0"
edition = "2021"
description = "A Graphical User Interface for interacting with local and remote Raspberry Pi Hardware"
default-run = "piggui"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>", "Sundaram Krishnan <krishnsundaram@gmail.com>"]
license = "Apache-2.0"
documentation = "https://github.com/andrewdavidmackenzie/pigg/README.md"
repository = "https://github.com/andrewdavidmackenzie/pigg/"
readme = "README.md"

[[bin]]
name = "piggui"
path = "src/piggui.rs"
required-features = ["gui"]

[[bin]]
name = "piglet"
path = "src/piglet.rs"

[features]
default = ["fake_hw"]
pi_hw = ["rppal"]
fake_hw = []
gui = ["iced", "iced_futures", "rfd", "plotters-iced", "plotters", "getrandom/js"]

[dependencies]
# use in piggui and piglet
chrono = { version = "0.4", default-features = false, features = ["now", "wasmbind", "wasm-bindgen", "js-sys"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.118" }
rand = { version = "0.8.5" }
clap = { version = "4.5.7" }

# for interacting with GPIO on the Raspberry Pi
rppal = { version = "0.18.0", optional = true }

# used in piglet only
log = "0.4.21"
env_logger = "0.11.3"

# used by piggui in GUI only
iced = { version = "0.12.1", default-features = false, features = ["tokio", "debug", "canvas", "advanced", "webgl"], optional = true }
iced_aw = { version = "0.9.3", default-features = false, features = ["tabs", "card", "modal", ], optional = true }
iced_futures = { version = "0.12.0", default-features = false, optional = true }
iced_native = { version = "0.10.3", optional = true }
rfd = { version = "0.14.1", optional = true }
plotters-iced = { version = "0.10", optional = true }
plotters = { version = "0.3", optional = true, default_features = false, features = [
    "chrono",
    "line_series",
] }
getrandom = { version = "0.2", features = ["js"]}

[dev-dependencies]
tempfile = "3"
```
Your help in addressing this issue is greatly appreciated.
Thx in advance!
