### ISSUE TITLE
Cannot link against items in `wasm_bindgen_futures` from third-party crates

### ISSUE THREAD

**Issue by allsey87** [rustwasm/wasm-bindgen#4164]
### Summary

I am writing the documentation for my crate and trying to link against items inside of `wasm_bindgen_future` without much success. For example, when I try to link against `wasm_bindgen_future::spawn_local`:
```
//! See [`wasm_bindgen_future::spawn_local`]
```

 the output just renders as `[wasm_bindgen_future::spawn_local]` instead of [`wasm_bindgen_future::spawn_local`](https://docs.rs/wasm-bindgen-futures/latest/wasm_bindgen_futures/fn.spawn_local.html). `cargo doc` produces no warning or errors, however,  I can see that the item is highlighted as a function (in vscode with rust analyzer) when it exactly matches. This seems to suggest that vscode can find the item being referenced while rustdoc cannot.

### Additional Details

I have the following configuration under .cargo/config.toml. Not sure if this is relevant...
```toml
[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
```
