### ISSUE TITLE
Publish a `wasm-bindgen-test` for use as an internal detail within `wasm-pack test`

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#615]
As discussed in today's WG meeting, we are aiming for publishing an initial release of the `wasm-bindgen-test` crate to be used as an unstable implementation detail within a `wasm-pack test` command for the Rust 2018 Release Candidate milestone. That's 6 weeks from now: 2018-09-13.

What needs to be done before we publish `wasm-bindgen-test` for use by `wasm-pack test`?

+cc @alexcrichton @ashleygwilliams

**Comment by fitzgen** [comment]
And here is the `wasm-pack` half: https://github.com/rustwasm/wasm-pack/issues/248

**Comment by gnzlbg** [comment]
So I followed the steps here https://github.com/rustwasm/wasm-bindgen/blob/master/crates/test/README.md

And got the following error: https://gist.github.com/gnzlbg/bce2a1020dde236e28d466311e4697c8

System is MacOSX 10.13.6 
I installed node via homebrew: `brew install node`, which installed the version 10.8.0

My `Cargo.toml` looks like: 

```toml
[package]
name = "wasm-test"
version = "0.1.0"
authors = ["..."]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { git = 'https://github.com/rustwasm/wasm-bindgen' }
```

and in my `wasm-test` binary crate, I have a `.cargo/config` that looks like:

```toml
[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
```

My `src/main.rs` is just an `fn main() {}`, and the `tests/test.rs` is the one in the Readme.
