### ISSUE TITLE
wasm-bindgen fails to process wasm generated with LTO

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#864]
When I enable LTO on my wasm project, wasm-bindgen aborts with the following:
```
wasm-bindgen rust/out/calories_calc.wasm \
		--no-modules --out-dir out
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(18)`,
 right: `Some(0)`', /Users/upsuper/.cargo/git/checkouts/wasm-bindgen-340397a49d85992c/f871cf6/crates/wasm-interpreter/src/lib.rs:349:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: wasm_bindgen_wasm_interpreter::Interpreter::call
   8: wasm_bindgen_wasm_interpreter::Interpreter::interpret_closure_descriptor
   9: wasm_bindgen_cli_support::js::closures::rewrite
  10: wasm_bindgen_cli_support::js::Context::finalize
  11: wasm_bindgen_cli_support::Bindgen::_generate
  12: wasm_bindgen::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: std::rt::lang_start_internal
  17: main
```

I can probably try reduce the code if that would help.

**Comment by alexcrichton** [comment]
Thanks for the report! A way to reproduce would be great, and a reduction would be amazing! (a reduction isn't required though)

**Comment by upsuper** [comment]
A relatively simplified reproduction:

Cargo.toml:
```toml
[package]
name = "x"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
lazy_static = "1.1.0"
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }

[dependencies.web-sys]
git = "https://github.com/rustwasm/wasm-bindgen"
features = [
    "Document",
    "Event",
    "EventTarget",
    "Window",
]
```

lib.rs:
```rust
use lazy_static::lazy_static;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Document, Event, EventTarget, Window, window};

lazy_static! {
    static ref WIN: Window = window().unwrap();
    static ref DOC: Document = WIN.document().unwrap();
}

macro_rules! add_listener {
    (($target:expr, $type:expr) => |$evt:ident| $block:block) => {{
        let func: Box<dyn FnMut(_) -> Result<_, JsValue>> = Box::new(|$evt: Event| $block);
        let closure = Closure::wrap(func);
        let result = ($target.as_ref() as &EventTarget)
            .add_event_listener_with_callback($type, closure.as_ref().unchecked_ref());
        closure.forget();
        result
    }};
}

#[wasm_bindgen]
pub fn init() -> Result<(), JsValue> {
    add_listener!((DOC, "DOMContentLoaded") => |_evt| {
        Ok(())
    })
}
```

commands:
```
cargo +nightly build --release --target wasm32-unknown-unknown
wasm-bindgen target/wasm32-unknown-unknown/release/calories_calc.wasm --out-dir .
```

This reports:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(1)`,
 right: `Some(0)`', /Users/upsuper/.cargo/git/checkouts/wasm-bindgen-340397a49d85992c/f871cf6/crates/wasm-interpreter/src/lib.rs:349:25
```
