### ISSUE TITLE
TypeScript: Invalid output `constructor: ;` in 0.2.23

### ISSUE THREAD

**Issue by emk** [rustwasm/wasm-bindgen#917]
Wow, the latest release of `wasm-bindgen` is absolutely amazing!

I might have found a little bug in the TypeScript generation, though.

Using this `Cargo.toml` file:

```toml
[package]
name = "wasm-bindgen-ts-constructor"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
```

And this `src/lib.rs` file:

```rust
extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Demo(u8);

#[wasm_bindgen]
impl Demo {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Demo {
        Demo(0)
    }
}
```

Run the following:

```sh
cargo build --target wasm32-unknown-unknown --release
mkdir -p out
wasm-bindgen target/wasm32-unknown-unknown/release/wasm_bindgen_ts_constructor.wasm --out-dir out --no-modules
```

This will generate the following `wasm_bindgen_ts_constructor.d.ts` file:

```ts
/* tslint:disable */
export class Demo {
free(): void;
 constructor(): ;

}
```

The `constructor(): ;` syntax appears to be invalid.

Expected output: `constructor();`.

Thank you for a really promising tool!
